# Generated by Django 3.0.8 on 2020-07-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
